---
- name: Create the .ssh directory for root
  file:
    path: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Create the SSH private key file
  copy:
    dest: /root/.ssh/id_rsa
    content: "{{ v2v_ssh_private_key }}"
    owner: root
    mode: 0600
