export const FETCH_V2V_SOURCE_DATASTORES = 'FETCH_V2V_SOURCE_DATASTORES';
export const FETCH_V2V_TARGET_DATASTORES = 'FETCH_V2V_TARGET_DATASTORES';
export const REMOVE_V2V_TARGET_DATASTORE = 'REMOVE_V2V_TARGET_DATASTORE';
export const REMOVE_V2V_SOURCE_DATASTORES = 'REMOVE_V2V_SOURCE_DATASTORES';
export const ADD_V2V_TARGET_DATASTORE = 'ADD_V2V_TARGET_DATASTORE';
export const ADD_V2V_SOURCE_DATASTORES = 'ADD_V2V_SOURCE_DATASTORES';
