export const FETCH_V2V_SOURCE_CLUSTERS = 'FETCH_V2V_SOURCE_CLUSTERS';
export const FETCH_V2V_SOURCE_CLUSTERS_PENDING =
  'FETCH_V2V_SOURCE_CLUSTERS_PENDING';
export const FETCH_V2V_SOURCE_CLUSTERS_FULFILLED =
  'FETCH_V2V_SOURCE_CLUSTERS_FULFILLED';
export const FETCH_V2V_SOURCE_CLUSTERS_REJECTED =
  'FETCH_V2V_SOURCE_CLUSTERS_REJECTED';
