export const FETCH_SOURCE_CLUSTERS = 'FETCH_SOURCE_CLUSTERS';
export const FETCH_SOURCE_CLUSTERS_PENDING = 'FETCH_SOURCE_CLUSTERS_PENDING';
export const FETCH_SOURCE_CLUSTERS_FULFILLED =
  'FETCH_SOURCE_CLUSTERS_FULFILLED';
export const FETCH_SOURCE_CLUSTERS_REJECTED = 'FETCH_SOURCE_CLUSTERS_REJECTED';
