export const V2V_EDIT_PLAN_TITLE_SHOW_ALERT = 'V2V_EDIT_PLAN_TITLE_SHOW_ALERT';
export const V2V_EDIT_PLAN_TITLE_HIDE_ALERT = 'V2V_EDIT_PLAN_TITLE_HIDE_ALERT';
export const V2V_POST_EDIT_PLAN_TITLE = 'V2V_POST_EDIT_PLAN_TITLE';
