export const QUERY_V2V_OSP_TENANT_ATTRIBUTES = 'QUERY_V2V_OSP_TENANT_ATTRIBUTES';
export const SET_V2V_INSTANCE_PROPERTIES_ROWS = 'SET_V2V_INSTANCE_PROPERTIES_ROWS';
export const QUERY_V2V_OSP_BEST_FIT_FLAVOR = 'QUERY_V2V_OSP_BEST_FIT_FLAVOR';
export const SET_V2V_BEST_FIT_FLAVORS_AND_DEFAULT_SECURITY_GROUPS =
  'SET_V2V_BEST_FIT_FLAVORS_AND_DEFAULT_SECURITY_GROUPS';
export const PLAN_WIZARD_EXITED = 'PLAN_WIZARD_EXITED';
export const SET_UPDATED_INSTANCE_PROPERTIES_ROW_ON_STANDBY = 'SET_UPDATED_INSTANCE_PROPERTIES_ROW_ON_STANDBY';
