// reminder... we need to go back and prefix these: V2V_
export const SHOW_MAPPING_WIZARD = 'SHOW_MAPPING_WIZARD';
export const HIDE_MAPPING_WIZARD = 'HIDE_MAPPING_WIZARD';
export const MAPPING_WIZARD_EXITED = 'MAPPING_WIZARD_EXITED';
export const SHOW_PLAN_WIZARD = 'SHOW_PLAN_WIZARD';
export const HIDE_PLAN_WIZARD = 'HIDE_PLAN_WIZARD';
export const PLAN_WIZARD_EXITED = 'PLAN_WIZARD_EXITED';
export const CONTINUE_TO_PLAN = 'CONTINUE_TO_PLAN';

export const FETCH_V2V_TRANSFORMATION_MAPPINGS =
  'FETCH_V2V_TRANSFORMATION_MAPPINGS';

export const FETCH_V2V_TRANSFORMATION_PLANS = 'FETCH_V2V_TRANSFORMATION_PLANS';

export const CREATE_V2V_TRANSFORMATION_PLAN_REQUEST =
  'CREATE_V2V_TRANSFORMATION_PLAN_REQUEST';
