---
- include_tasks: "check-transport-vddk-facts.yml"

- name: Assert that VDDK library is installed
  assert:
    that: "{{ v2v_vddk_library_installed }}"
    msg: "VDDK library is not installed"

- name: Assert that VDDK nbdkit plugin is installed
  assert:
    that: "{{ v2v_nbdkit_plugin_installed }}"
    msg: "VDDK nbdkit plugin is not installed"

- name: Assert that VDDK nbdkit plugin test succeeded
  assert:
    that: "{{ v2v_nbdkit_plugin_working }}"
    msg: "VDDK nbdkit plugin failed validation"
