---
- name: Stat VDDK library
  stat:
    path: "{{ v2v_vddk_install_dir }}/vmware-vix-disklib-distrib/lib64/libvixDiskLib.so"
  ignore_errors: "yes"
  register: stat_vddk_library

- name: Assert that VDDK library is installed
  assert:
    that: "{{ stat_vddk_library.stat.exists }}"
    msg: "VDDK library is not installed"
