export const FETCH_V2V_SOURCE_CLUSTERS = 'FETCH_V2V_SOURCE_CLUSTERS';
export const FETCH_V2V_TARGET_CLUSTERS = 'FETCH_V2V_TARGET_CLUSTERS';
export const REMOVE_TARGET_CLUSTER = 'REMOVE_TARGET_CLUSTER';
export const REMOVE_SOURCE_CLUSTERS = 'REMOVE_SOURCE_CLUSTERS';
