export const POST_V2V_MIGRATION_PLANS = 'POST_V2V_MIGRATION_PLANS';
export const PUT_V2V_MIGRATION_PLANS = 'PUT_V2V_MIGRATION_PLANS';
export const POST_V2V_MIGRATION_REQUESTS = 'POST_V2V_MIGRATION_REQUESTS';
